apiVersion: v1
kind: ServiceAccount
metadata:
  name: pending-watcher-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: pending-watcher
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pending-watcher-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: pending-watcher-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: pending-watcher
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pending-watcher
  namespace: default
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pending-watcher
  template:
    metadata:
      labels:
        app: pending-watcher
    spec:
      serviceAccountName: pending-watcher-sa
      containers:
      - name: watcher
        image: ghcr.io/shadi/pending-watcher:7a375ba
        args: 
        - --mode
        - repeat
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: pending-watcher
            topologyKey: "kubernetes.io/hostname" 
