name: Build, Test and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.23

    - name: Build binary
      run: CGO_ENABLED=0 GOARCH=amd64 go build -ldflags="-w -s" -o pending-watcher

    - name: Set short git commit SHA
      id: vars
      run: |
        short=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=short_sha::$short"

    - name: 'Login to ghcr'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: | 
          ghcr.io/shadi/pending-watcher:latest
          ghcr.io/shadi/pending-watcher:${{ steps.vars.outputs.short_sha }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pending-watcher
        tag: ${{ github.ref }}
        overwrite: true
